services:
  bookstore-api:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings:DefaultConnection=Server=bookstore-db-sql;Database=BookstoreDbDev;User=sa;Password=${SA_PASSWORD?err};TrustServerCertificate=True;"
      - "DataAccess:UseMockDataAccess=${USE_MOCK_DATA_ACCESS?err}"
      - "AllowedOrigins=http://localhost:3000"
    ports:
      - 5000:80
